name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install scikit-build cmake pybind11 pytest

      - name: Configure C++ core + bindings
        run: |
          cmake -S core -B build/core -DCMAKE_BUILD_TYPE=Release
          cmake -S bindings/python -B build/python -DCMAKE_BUILD_TYPE=Release

      - name: Build core lib and tests
        run: cmake --build build/core --config Release

      - name: Build C++ CLI binary
        run: cmake --build build/core --target grimoire_demo --config Release

      - name: Build Python bindings
        run: cmake --build build/python --config Release

      - name: Run C++ tests
        run: ctest --test-dir build/core --output-on-failure --verbose -C Release

      - name: Run Python bindings tests
        run: |
          export PYTHONPATH=$PWD/build/python
          pytest bindings/python/test/ -v --tb=short
