name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Install Python build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install scikit-build cmake pybind11 pytest

      - name: Configure C++ core library
        run: cmake -S core -B build/core -DCMAKE_BUILD_TYPE=Debug

      - name: Build C++ core library
        run: cmake --build build/core --config Debug

      - name: Run C++ unit tests
        run: ctest --test-dir build/core --output-on-failure --verbose -C Debug

      - name: Build and install Python bindings (wheel)
        working-directory: bindings/python
        run: pip install . -v

      - name: Verify Python module location
        run: |
          python -m site
          find $(python -c "import site; print(site.getsitepackages()[0])") | grep grimoire

      - name: Verify import works
        run: python -c "import grimoire_diag; print('grimoire_diag module found')"

      - name: Run Python bindings tests
        working-directory: bindings/python
        run: pytest test/ -v --tb=short
