name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Configure C++ core library
        run: cmake -S core -B build/core -DCMAKE_BUILD_TYPE=Release

      - name: Build C++ core library
        run: cmake --build build/core --config Release

      - name: Run C++ unit tests
        run: ctest --test-dir build/core --output-on-failure --verbose -C Release

      - name: Configure Python bindings
        run: cmake -S bindings/python -B build/python -DCMAKE_BUILD_TYPE=Release

      - name: Build Python bindings
        run: cmake --build build/python --config Release

      - name: List built Python extension
        run: find build/python

      - name: Run Python bindings tests
        run: |
          export PYTHONPATH=$PWD/build/python
          pytest bindings/python/test/ -v --tb=short
