name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Build C++ and bindings
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Run C++ Unit Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Run Python Tests
        run: |
          cd python/test
          python test_diag.py
          python test_shared_log.py
